### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by srinath1412001**
Added  a link to  the page containing contribution guidelines

### CODE REVIEW

**Comment by mal-tee** [comment]
Thank you! This is something we would have added in the future, now we don't have to :)
But this is a minor improvement, we would like it very much if you could extend this WIP Readme to become a fully fledged one. 

A few things that come to my mind:

- specify which endpoints are defined by the backend (see https://github.com/datenanfragen/backend/blob/master/src/index.js) 
- explain the config entries
  - we already explained mollie and CoinGate of `donation`
  - `email`, `comments`, `suggest`
  - Please link the Github Page on how to obtain an API token and explain that the token needs the right permissions
  - if you want to, you could also explain the `hacktoberfest `config, but because it is only needed one month a year you could skip it 

If you come up with other important things feel free to add them.

Please let us know if you want to make these changes and thank you.

**Review by mal-tee — CHANGES_REQUESTED** [review]
Thank you! This is something we would have added in the future, now we don't have to :)
But this is a minor improvement, we would like it very much if you could extend this WIP Readme to become a fully fledged one. 

A few things that come to my mind:

- specify which endpoints are defined by the backend (see https://github.com/datenanfragen/backend/blob/master/src/index.js) 
- explain the config entries
  - we already explained mollie and CoinGate of `donation`
  - `email`, `comments`, `suggest`
  - Please link the Github Page on how to obtain an API token and explain that the token needs the right permissions
  - if you want to, you could also explain the `hacktoberfest `config, but because it is only needed one month a year you could skip it 

If you come up with other important things feel free to add them.

Please let us know if you want to make these changes and thank you.

**Comment by srinath1412001** [comment]
Hey @mal-tee,
Thank you for the feedback. I am not familiar working with Backend and APIs. If you could guide me, I will definitely try my best to fulfill your requirements.

**Comment by mal-tee** [comment]
Sure, great! :D

- Check the index.js for the `server.route` calls. They define the things the backend can do. The path and method parameters specify under which path they are available with which [HTTP method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods). The different names should be pretty self-explanatory. You could list them all in the README and give a short comment on what they do.
  - E.g. : - PUT `/comments` - Submit a new comment for review
- https://github.com/settings/tokens is the GH page for getting tokens for the `suggest `config

**Comment by zner0L** [comment]
One important thing to mention: The account the token belongs to needs to have the "Triage" role for the repository in question. We need this, so that the backend can add labels to the PRs.

**Comment by mal-tee** [comment]
And atm the token has all `repo` permissions. This might be too much, but it's how we operate and how we should document it.

**Comment by srinath1412001** [comment]
Is it ok if I work on it from next week? (after 6th October). I have my college exams till then.

**Comment by mal-tee** [comment]
Of course! This is not time-sensitive. Good Luck with your exams.

**Comment by srinath1412001** [comment]
@mal-tee thank you :)
I'm sure that I'm going to learn something  making these changes.

**Comment by srinath1412001** [comment]
I'm Sorry,
I don't think I can work on it.
I'll close the pull request.

**Comment by mal-tee** [comment]
Okay, but thank you again!

**Pull request closed without merging**
